ci:
    skip: [ggshield, go-mod-tidy, golangci-lint-repo-mod]

repos:

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.44.0
    hooks:
      - id: markdownlint
        name: markdown linting

  - repo: https://github.com/thlorenz/doctoc
    rev: v2.2.0
    hooks:
      - id: doctoc
        name: update toc
        args: ["--update-only"]

  - repo: https://github.com/gitguardian/ggshield
    rev: v1.38.1
    hooks:
      - id: ggshield
        name: gitguardian scanning

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        name: trailing whitespace
      - id: end-of-file-fixer
        name: end of file fixer
      - id: check-added-large-files
        name: check added large files
      - id: check-yaml
        name: check yaml
      - id: check-json
        name: check json

  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      - id: go-mod-tidy
        name: golang tidying
      - id: golangci-lint-repo-mod
        name: golang linting
