version: 3

silent: true

tasks:
  default:
    desc: initialise local environment
    cmds:
      - task: init

  init:
    desc: initialise local environment
    cmds:
      - task: pre-commit:init
      - task: test:global
      - task: todo

  pre-commit:init:
    desc: initialises pre-commit hooks
    cmds:
      - pre-commit autoupdate
      - pre-commit install

  pre-commit:run:
    desc: run pre-commit hooks without caches
    deps: ["pre-commit:init"]
    cmds:
      - pre-commit run --all-files

  test:global:
    desc: copies a global config file to expected location
    cmds:
      - rm -f ~/.config/.neat.yaml
      - cp ./config/.neat-global.yaml ~/.config/.neat.yaml

  build:
    desc: builds locally using goreleaser
    cmds:
      - goreleaser build --rm-dist --snapshot

  todo:
    desc: shows the todo list
    cmds:
      - glow TODO.md
    preconditions:
      - stat TODO.md
