version: 3

silent: true

tasks:
  default:
    desc: initialise local environment
    cmds:
      - task: init

  init:
    desc: initialise local environment
    cmds:
      - task: pre-commit:init
      - task: test:global
      - task: test:repo
      - task: todo

  pre-commit:init:
    desc: initialises pre-commit hooks
    cmds:
      - pre-commit autoupdate
      - pre-commit install

  pre-commit:run:
    desc: run pre-commit hooks without caches
    deps: ["pre-commit:init"]
    cmds:
      - pre-commit run --all-files

  test:global:
    desc: copies a global config file to expected location
    cmds:
      - cp ./config/.neat.yaml ~/.config/.neat.yaml

  test:repo:
    desc: creates a test repo at /tmp/go-neat-test
    cmds:
      - rm -rf $GIT_WORK_TREE
      - git init $GIT_WORK_TREE
      - cp -a ./test/. $GIT_WORK_TREE
      - git add .
      - git commit -m 'something'
    env:
        GIT_WORK_TREE: /tmp/go-neat-test
        GIT_DIR: /tmp/go-neat-test/.git

  build:
    desc: builds locally using goreleaser
    cmds:
      - goreleaser build --rm-dist --snapshot

  todo:
    desc: shows the todo list
    cmds:
      - glow TODO.md
    preconditions:
      - stat TODO.md
